### ISSUE TITLE
Please update dql-index.md to fix the confusing nbEmployeesMax example

### ISSUE THREAD

**Issue by gmsh** [diffbot/docs#100]
Please change the `Max` to `Min` in the example in line 75.

Logically, if the `nbEmployeesMax >= 5000`, then the `nbEmployeesMin` could be less than 5000. For example, the actual number of employees for a company is 10, and our estimation is [5, 10000], a very loose range. And  `nbEmployeesMax >= 5000` will match this company, but we couldn’t say the number of employees of it is more than 5000, right?

https://github.com/diffbot/docs/pull/99

**Comment by Swader** [comment]
Closed in #99
